---
title: "4b. Capricorn Bunkers, sGBR"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{workflow}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

```{r eval=TRUE, message=FALSE, warning=FALSE, include=FALSE, echo=FALSE}
library(devtools)

load_all()
conflicted::conflicts_prefer(dplyr::filter)
```

Example from the southern Northern GBR

```{r fig.height=9, fig.width=12, message=FALSE, warning=FALSE, cache=TRUE}


library(coastalwaves)
library(dhw)
library(sf)
library(tidyverse)
library(lubridate)
library(ggplot2)


### download GBR shape file
gbr_shape <- download_gbr_spatial(return = "base") |>
  select(LOC_NAME_S, X_COORD, Y_COORD) |> 
  st_make_valid() |> 
  st_transform(20353)

### Grep subset for target reefs, create union
fn_capricorn <- gbr_shape |> 
  filter(grepl("23-052|23-053", LOC_NAME_S))

fn_capricorn_union <- fn_capricorn |>
  st_union() |>
  st_boundary() |>
  st_cast("LINESTRING")

# Extract broader region
fn_capricorn_region <- st_crop(gbr_shape, 
                             fn_capricorn_union |>
                                st_union() |> 
                                st_centroid() |> 
                                st_buffer(20000))

# get points
fn_capricorn_points <- calculate_points(fn_capricorn_union, 100)


### calculate fetch
fn_capricorn_fetch <- calculate_fetch(point = fn_capricorn_points, 
                                     degrees = 7.5, 
                                     fetch = 5000, 
                                     land = fn_capricorn_region, 
                                     parallel = TRUE, 
                                     cores = 8)


### get wind data
#fn_capricorn_wind <- get_wind_data(fn_capricorn, "1997-01-01", "1997-12-31")

#fn_capricorn_wind <- get_wind_data(st_centroid(st_union(fn_capricorn)), "1989-09-01", "1989-09-10")
fn_capricorn_wind <- read.csv("/Users/rof011/coastalwaves/data/df_sgbr.csv") |> rename(windspeed_ms = wspeed, date=time)

### get waves
fn_capricorn_waves <- calculate_wave_exposure(wind = fn_capricorn_wind, 
                                     fetch = fn_capricorn_fetch, 
                                     points = fn_capricorn_points, 
                                     parallel = TRUE, 
                                     cores = 8) 


fn_capricorn_wave_grid <- create_wave_grid(fn_capricorn_union, fn_capricorn_waves, interval = 100, width = 100)


library(tmap) 
tmap_mode("view") +
tm_basemap("Esri.WorldImagery") +
tm_shape(fn_capricorn_wave_grid) +
  tm_polygons(fill="wave_energy_total", shape=21, size=0.8,
              fill.scale=tm_scale_continuous(values="-brewer.spectral"))


```
